service: household-account-book

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "dynamodb:*"
     Resource: "arn:aws:dynamodb:*"

functions:
  account:
    handler: handler.handler
    events:
      - http:
          path: account
          method: post
  asyncAggregate:
    handler: aggregate.handler
    events:
      - schedule: cron(0 0 1 * ? *)

resources:
  Resources:
    # ref: http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-attributedef
    TemplateDynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: household-account-books
        AttributeDefinitions:
          - AttributeName: category
            AttributeType: S # String:S Number:N Binary:B
          - AttributeName: createdAt
            AttributeType: N
        KeySchema:
          - AttributeName: category
            KeyType: HASH # HASH or RANGE
          - AttributeName: createdAt
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
